version: "3.9"
services:
  op-geth-genesis:
    image: "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:latest"
    command:
      - init
      - --datadir=/data
      - /config/genesis.json
    volumes:
      - ./data/op-geth:/data
      - ./l2-config:/config

  op-geth:
    image: "ghcr.io/longfin/op-geth:v1.101106.0-eip-7212"
    command:
      - --datadir=/data
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.api=web3,debug,eth,txpool,net,engine
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=debug,eth,txpool,net,engine
      - --syncmode=full
      - --gcmode=archive
      - --nodiscover
      - --maxpeers=0
      - --networkid=42069
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/config/jwt.txt
      - --rollup.disabletxpoolgossip=true
    volumes:
      - ./data/op-geth:/data
      - ./l2-config:/config
    ports:
      - 18545:8545
    depends_on:
      op-geth-genesis:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8551"]
      interval: 15s
      start_period: 10s

  op-node:
    image: "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest"
    command:
      - op-node
      - --l2=http://op-geth:8551
      - --l2.jwt-secret=/config/jwt.txt
      - --sequencer.enabled
      - --sequencer.l1-confs=3
      - --verifier.l1-confs=3
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --rpc.port=8547
      - --p2p.disable
      - --rpc.enable-admin
      - --p2p.sequencer.key=${OP_SEQ_KEY}
      - --l1=http://geth:8545
      - --l1.rpckind=any
      - --log.level=debug
    volumes:
      - ./data/op-node:/data
      - ./l2-config:/config    
    depends_on:
      op-geth:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8547"]
      interval: 15s
      start_period: 10s

  op-batcher:
    image: "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:latest"
    command:
      - --l1-eth-rpc=http://geth:8545
      - --l2-eth-rpc=http://op-geth:8545
      - --rollup-rpc=http://op-node:8547
      - --poll-interval=1s
      - --sub-safety-margin=6
      - --num-confirmations=1
      - --safe-abort-nonce-too-low-count=3
      - --resubmission-timeout=30s
      - --rpc.addr=0.0.0.0
      - --rpc.port=8548
      - --rpc.enable-admin
      - --max-channel-duration=1
      - --private-key=${OP_BATCHER_KEY}
    depends_on:
      op-node:
        condition: service_healthy

  op-proposer:
    image: "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:latest"
    command:
      - op-proposer
      - --poll-interval=12s
      - --rpc.port=8560
      - --rollup-rpc=http://op-node:8547
      - --l2oo-address=${OP_OO_ADDR}
      - --private-key=${OP_PROPOSER_KEY}
      - --l1-eth-rpc=http://geth:8545
    depends_on:
      op-node:
        condition: service_healthy

  aa-bundler:
    image: "ghcr.io/longfin/stackup-bundler:v0.6.14"
    environment:
      - ERC4337_BUNDLER_ETH_CLIENT_URL=http://op-geth:8545
      - ERC4337_BUNDLER_PRIVATE_KEY=${AA_BUNDLER_KEY}
    ports:
      - 14337:4337
    depends_on:
      op-geth:
        condition: service_healthy

