version: "3.9"
services:
  genesis-generator:
    build: genesis-generator
    command:
      - all
    volumes:
      - ./data/genesis-generator:/data
      - ./genesis-config:/config
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 15s
      start_period: 10s
  
  geth-genesis:
    image: "ethereum/client-go:latest"
    command: --datadir=/execution init /genesis/custom_config_data/genesis.json
    volumes:
      - ./data/genesis-generator:/genesis
      - ./data/execution:/execution
    depends_on:
     genesis-generator:
        condition: service_healthy

  geth:
    image: "ethereum/client-go:latest"
    command:
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/genesis/el/jwtsecret
      - --datadir=/execution
      - --nat=extip:15.168.63.137
      - --networkid=133711
      - --nodiscover
      - --syncmode=full
    ports:
      - 8551:8551
      - 8545:8545
      - 30303:30303
    depends_on:
      geth-genesis:
        condition: service_completed_successfully
    volumes:
      - ./data/execution:/execution
      - ./data/genesis-generator:/genesis
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8551"]
      interval: 15s
      start_period: 10s

  beacon-chain:
    image: "sigp/lighthouse:latest"
    command:
      - lighthouse
      - beacon_node
      - --http-address=0.0.0.0
      - --http-allow-sync-stalled
      - --execution-endpoint=http://geth:8551
      - --execution-jwt=/genesis/el/jwtsecret
      - --datadir=/consensus/beacon
      - --testnet-dir=/genesis/custom_config_data
      - --disable-packet-filter
      - --disable-peer-scoring
      - --staking
    depends_on:
      geth:
        condition: service_healthy
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
      - 5052:5052
    volumes:
      - ./data/consensus:/consensus
      - ./data/genesis-generator:/genesis

  validator-recover-wallet:
    image: "sigp/lighthouse:latest"
    command:
      - lighthouse
      - account_manager
      - validator
      - recover
      - --count=4
      - --datadir=/validator
      - --mnemonic-path=/genesis/custom_config_data/mnemonics.txt
    volumes:
      - ./data/validator:/validator
      - ./data/genesis-generator:/genesis
    depends_on:
      genesis-generator:
        condition: service_healthy

  validator:
    image: "sigp/lighthouse:latest"
    command:
      - lighthouse
      - validator
      - --init-slashing-protection
      - --datadir=/validator
      - --beacon-nodes=http://beacon-chain:5052
      - --testnet-dir=/genesis/custom_config_data
      - --suggested-fee-recipient=${FEE_RECIPIENT}
    depends_on:
      beacon-chain:
        condition: service_started
      validator-recover-wallet:
        condition: service_completed_successfully
    volumes:
      - ./data/consensus:/consensus
      - ./data/validator:/validator
      - ./data/genesis-generator:/genesis
